#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>
#include <sys/time.h>
#include <time.h>

#include "bfs.c"

int main()
{
    struct timeval startTime, stopTime;
    uint64_t results[TEST_RUNS];
    /* Create a Graph */
    graph *g = malloc(sizeof(graph));
    initialize_graph(g, false);

    /* Feed in graph data from STDIN */
    read_graph(g, false);
    printf("Reading Graph from STDIN complete\n");

    /* Print the contents of the graph if desired */
    // print_graph(g);
    printf("Starting Tests\n");
    for (int i = 0; i < TEST_RUNS; i++)
    {
        printf("Running test %d out of %d\n", i, TEST_RUNS);
        initialize_search(g);
        // Get a random vertex from the graph
        gettimeofday(&startTime, NULL);
        srand(startTime.tv_usec);
        uint64_t start = rand() % (g->number_vertices - 1);

        // Initiate BFS
        bfs(g, start);
        gettimeofday(&stopTime, NULL);

        // Print the Parents List generated by the BFS to STDOUT
        results[i] = stopTime.tv_usec - startTime.tv_usec;
    }
    printf("Printing last results to prove correctness:\n");
    print_parents(g);
    unsigned long avg = 0;
    unsigned long sum = 0;
    for (int i = 0; i < TEST_RUNS; i++)
    {
        printf("Test %d: %luns\n", i, results[i]);
        sum += results[i];
    }
    avg = sum / TEST_RUNS;
    printf("Averaged over %d iterations, Time: %luns\n", TEST_RUNS, avg);

    return 0;
}