#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <time.h>
#include <mpi.h>
#include "aml.h"
#include "aml.c"
#include "constants.h"
#include "globals.c"
#include "bfs.c"

int main(int argc, char *argv[])
{
    /* Problem Vars */
    unsigned long start;

    /* MPI Setup */
    aml_init(&argc, &argv); //includes MPI_Init inside
    createGlobals();
    aml_barrier();
    read_graph();
    printf("Did I get here?\n");

    // /* Process 0 generates a random start vertex and sends a message to the process owning that vertex*/
    if (processId == 0)
    {
        // Get a random vertex from the graph
        srand(time(0));
        printf("# Vertices: %lu\n", g->number_vertices);
        start = rand() % (g->number_vertices - 1);
        printf("%d generated random start of %lu\n", processId, start);
        printf("%d is telling %d to start BFS\n", processId, start % noProcesses);
        // Initiate BFS
        aml_send(&start, 5, sizeof(&start), start % noProcesses); /* bfsHandler */

        // Print the Parents List generated by the BFS to STDOUT
        // print_parents(g);
    }
    else
    {
        /* This is a big hack to keep the processes other than 0 from hitting the barrier before 0 sends the start BFS message */
        sleep(1);
    }
    aml_barrier();
    aml_finalize(); //includes MPI_Finalize()
    cleanGlobals();
    return 0;
}